main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('snippets/', views.snippets, name="snippets"),
    path('snippets/new', views.new_snippet, name="new_snippet"),
    path('snippets/<int:snippet_id>/delete', views.delete_snippet, name="delete_snippet"),
    path('snippets/<int:snippet_id>/edit', views.edit_snippet, name="edit_snippet"),
    path('snippets/<int:snippet_id>/unassoc_tag/<int:tag_id>/', views.unassoc_tag, name="unassoc_tag"),
    path('snippets/<int:snippet_id>/findOrCreate_assoc_tag/', views.findOrCreate_assoc_tag, name="findOrCreate_assoc_tag"),
    path('groups/', views.groups, name="groups"),
    path('groups/new', views.new_group, name="new_group"),
    path('groups/<int:group_id>/delete/', views.delete_group, name="delete_group"),
    path('groups/<int:group_id>/assoc_tag_to_group/', views.assoc_tag_to_group, name="assoc_tag_to_group"),
    path('groups/<int:tag_id>/unassoc_tag_from_group/', views.unassoc_tag_from_group, name="unassoc_tag_from_group"),
    path('accounts/signup/',views.signup, name="signup"),
]

snippetcollector_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Group(models.Model):
    name = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=50)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name # {Group.objects.get(id=self.group_id).name}

class Snippet(models.Model):
    body = models.TextField(max_length=1000)
    tags = models.ManyToManyField(Tag, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['body','user_id'], name="unique_snippetbody_per_user")
        ]
        
    def __str__(self):
        return self.body

main_app/forms.py
from django import forms
from .models import Snippet, Group

class SnippetForm(forms.ModelForm):
    class Meta:
        model = Snippet
        fields = ['body']

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from .models import Group, Tag, Snippet
from .forms import SnippetForm, GroupForm

# Create your views here.
def home(request):
    return render(request, 'home.html')

@login_required
def snippets(request):
    # query all snippets
    snippets = Snippet.objects.filter(user=request.user)
    # query all groups
    groups = Group.objects.all()
    # send empty instance of SnippetForm
    snippet_form = SnippetForm()
    return render(request, 'snippets/index.html', {'snippets': snippets, 'snippet_form': snippet_form, 'groups': groups})

@login_required
def new_snippet(request):
    # populate snippet form with post data
    snippet_form = SnippetForm(request.POST)
    new_snippet = snippet_form.save(commit=False)
    new_snippet.user = request.user
    try:
        new_snippet.save()
    except:
        print('A snippet with that value already exists!')
    return redirect('snippets')

@login_required
def edit_snippet(request, snippet_id):
    # query snippet by id
    snippet = Snippet.objects.get(id=snippet_id)
    snippet.body = request.POST["body"]
    snippet.save()
    return redirect('snippets')

@login_required
def delete_snippet(request, snippet_id):
    # find snippet, delete it
    snippet = Snippet.objects.get(id=snippet_id)
    snippet.delete()
    return redirect('snippets')

@login_required
def findOrCreate_assoc_tag(request, snippet_id):
    # find snippet with provided id
    snippet = Snippet.objects.get(id=snippet_id)
    # find or create tag with provided id
    tag = Tag(name=request.POST['tag'])
    tag.save()
    # tag = Tag.objects.get(id=tag_id)
    # associate them
    snippet.tags.add(tag)
    return redirect('snippets')
    
@login_required
def unassoc_tag(request, snippet_id, tag_id):
    # find snippet with provided id
    snippet = Snippet.objects.get(id=snippet_id)
    # find tag with provided id
    tag = Tag.objects.get(id=tag_id)
    # unassociate them
    snippet.tags.remove(tag)
    return redirect('snippets')


@login_required
def groups(request):
    # query groups and send to template
    groups = Group.objects.filter(user=request.user)
    # send empty instance of GroupForm to template
    group_form = GroupForm()
    return render(request, 'groups.html', {'groups': groups, 'group_form': group_form})

@login_required
def new_group(request):
    # populate instance of GroupForm with post data
    group_form = GroupForm(request.POST)
    new_group = group_form.save(commit=False)
    new_group.user = request.user
    new_group.save()
    return redirect('groups')

@login_required
def delete_group(request, group_id):
    # query specific group to delete
    group = Group.objects.get(id=group_id)
    group.delete()
    return redirect('groups')

@login_required
def assoc_tag_to_group(request, group_id):
    # create tag from request-post data
    tag = Tag(name=request.POST['tag'], group_id=group_id)
    tag.save()
    return redirect('groups')

@login_required
def unassoc_tag_from_group(request, tag_id):
    # query for specific tag, remove foreign key
    tag = Tag.objects.get(id=tag_id)
    tag.group_id = None
    tag.save()
    return redirect('groups')

def signup(request):
    err_msg = ''
    form = UserCreationForm(request.POST or None)
    if request.method == 'POST':
        # return HttpResponse('<p>post</p>')
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('snippets')
        else:
            err_msg = 'Invalid signup.  Please try again.'
    return render(request, 'registration/signup.html', {'form': form, 'err_msg': err_msg})
        # return HttpResponse('<p>get</p>')

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}SnippetCollector{% endblock title %}</title>
    {% comment %} .h1 font {% endcomment %}
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Blinker&display=swap" rel="stylesheet">
    {% comment %} MATERIALIZE ICONS {% endcomment %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {% comment %} MATERIALIZE CSS {% endcomment %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    {% comment %} STATIC CSS {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% comment %} MATERIALIZE JS {% endcomment %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body>
    <nav class="nav-wrapper">
        <ul class="right">
            {% if user.is_authenticated %}
                <li style="color: #6df56d; margin-right: 20px;">Hi, {{user}}!</li>
                <li><a href="{% url 'snippets' %}">Snippets</a></li>
                <li><a href="{% url 'groups' %}">Groups</a></li>
                <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
                <li><a href="{% url 'home' %}">About</a></li>
                <li><a href="{% url 'signup' %}">Sign Up</a></li>
                <li><a href="{% url 'login' %}">Log In</a></li>
            {%  endif %}
        </ul>
    </nav>
    
    <main class="container">
        {% block content %}
        {% endblock content %}
    </main>
</body>
</html>

main_app/templates/groups.html
{% extends 'base.html' %}
{% block title %}Snippets - Groups{% endblock title %}
{% block content %}
<h1 class="h1">Group your tags!</h1>
<p><i>How it works:  If you search for a tag that is in a group, your search will also include other tags in that group!</i></p>
<p><i>Hint:  For any group to affect your search, add at least 2 tags to it!</i></p>

    <button class="btn-new-group">New Group</button>

    {% comment %} NEW GROUP {% endcomment %}
    <div class="card form-new-group" style="display: none;">
        <div class="card-content">
            <form method="POST" action="{% url 'new_group' %}">
                {% csrf_token %}
                {{group_form.as_p}}
                <input type="submit" value="+ group">
                <label>(The group name can be anything, it does not really matter. :)</label>
            </form>
        </div>
    </div>

{% comment %} RENDER EVERY GROUP {% endcomment %}
{% for group in groups %}
    <div class="card group" value="{{group.tag_set.all.count}}" style="opacity: 0.5">
        <div class="card-content">

            <p class="card-title">{{group.name}}</p>
            {% comment %} RENDER EVERY TAG IN THIS GROUP {% endcomment %}
            {% for tag in group.tag_set.all %}
                <form method="POST" action="{% url 'unassoc_tag_from_group' tag.id %}" class="inline-flex">
                    {% csrf_token %}
                    <input type="submit" value="{{tag.name}}" class="tag">
                </form>                
            {% endfor %}

            {% comment %} FIND-OR-CREATE TAG, ASSOCIATE IT {% endcomment %}
            <form method="POST" action="{% url 'assoc_tag_to_group' group.id %}" class="inline-flex">
                {% csrf_token %}
                <input type="text" name="tag" class="tag-input" style="text-transform: lowercase;" placeholder="some tag" required>
                <input type="submit" value="+ tag" class="add-tag">
            </form>

            {% comment %} DELETE GROUP {% endcomment %}
            <form method="POST" action="{% url 'delete_group' group.id %}">
                {% csrf_token %}
                <input type="submit" value="DELETE" style="position: absolute; bottom: 5px; right: 5px; color: salmon;">
            </form>

        </div>
    </div>
    {% empty %}
    <p>You have no groups.  :'(</p>
{% endfor %}



<script>
    const btnNewGroup = document.querySelector('.btn-new-group')
    const formNewGroup = document.querySelector('.form-new-group')

    //if a group has at last 2 tags inside, make it fully opaque
    const groups = document.querySelectorAll('.group')
    for (let group of groups) {
        if (parseInt(group.getAttribute('value')) >= 2) {
            group.style.opacity = '1'
        }
    }

    //click 'New Group' buttom to show/hide new group form
    btnNewGroup.addEventListener('click', () => {
        if (formNewGroup.style.display === 'none') {
            formNewGroup.style.display = 'block'
            btnNewGroup.textContent = '^collapse'
            const inputEl = formNewGroup.querySelector('#id_name')
            inputEl.focus()
        } else {
            formNewGroup.style.display = 'none'
            btnNewGroup.textContent = 'New Group'
        }
    })    
</script>
{% endblock content %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block title %}Snippets - About{% endblock title %}
{% block content %}
    <h1 class="h1">SnippetCollector</h1>
    <p>Are you a developer? A shortcut lover?  Someone who just wants quick access to bits of their information?  Introducing SnippetCollector!--an app where you can create 'snippets' of data and assign tags to them so that you can easily find them later via search bar!</p>

    <p><i>NEW FEATURE: GROUPS!</i> Tired of searching for a single-tense word, but not seeing results for other variations of it?  Now you can create groups of tags!  If you search for a tag that is part of a group, then your search will cleverly include all the tags of that group!</p>
{% endblock content %}

main_app/templates/snippets/index.html
{% extends 'base.html' %}
{% block title %}Snippets{% endblock title %}
{% block content %}
    <h1 class="h1">SnippetCollector</h1>

    {% comment %} RENDER ALL GROUPS (WITH AT LEAST TWO TAGS) AND HIDE THEM {% endcomment %}
    {% for group in groups %}
        {% if group.tag_set.all.count >= 2 %}
        <div class="card group" style="display: none">
            <div class="card-content">
                <p class="card-title">{{group.name}}</p>
                {% for tag in group.tag_set.all %}
                    <p class="group-tag">{{tag.name}}</p>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    {% endfor %}


    {% comment %} SEARCH BAR {% endcomment %}
    <div style="border: 1px solid black; padding: 5px 10px 0px 10px; background-color: #ffd1d1; margin-bottom: 10px;">
        <form class="form-search">
            <div class="input-field" style="display: flex;">
                <input type="search" class="search autocomplete" placeholder="search through your tags" style="background-color: white;" autofocus>
                <input type="submit" value="Search" style="height: 46px;">
            </div>
        </form>
    </div>

    <button class="btn-new-snippet">New Snippet</button>
    <div style="margin-bottom: 5px;"><label>Control + N</label></div>

    {% comment %} NEW SNIPPET (ModelForm) {% endcomment %}
    <div class="card div-new-snippet" style="display: none;">
        <div class="card-content">
            <form method="POST" action="{% url 'new_snippet' %}" class="form-new-snippet">
                {% csrf_token %}
                {{snippet_form.as_p}}
                <input type="submit" value="+ snippet" class="btn-plus-snippet">
                <p><label>Control + Enter</label></p>
            </form>
        </div>
    </div>

    {% comment %} RENDER ALL SNIPPETS {% endcomment %}
    <div class="cont-snippets">
        {% for snippet in snippets %}
            <div class="snippet" value="snippet{{snippet.id}}" style="position: relative;">
                {% comment %} RENDER SNIPPET {% endcomment %}
                <textarea class="textarea" readonly>{{ snippet.body }}</textarea>

                {% for tag in snippet.tags.all %}
                    {% comment %} RENDER TAG(S) - UNASSOC TAG FORM {% endcomment %}
                    <form method="POST" action="{% url 'unassoc_tag' snippet.id tag.id %}" class="inline-flex">
                        {% csrf_token %}
                        <input type="submit" value="{{tag.name}}" class="tag">
                    </form>
                {% endfor %}

                {% comment %} FIND-OR-CREATE, ASSOC TAG FORM {% endcomment %}
                <form  method="POST" action="{% url 'findOrCreate_assoc_tag' snippet.id %}" class="cont-add-tag">
                    {% csrf_token %}
                    <input type="text" placeholder="some-tag" name="tag" class="tag-input" style="text-transform: lowercase;" required>
                    <input type="submit" value="+ tag" class="add-tag">
                </form>

                {% comment %} EDIT SNIPPET MODAL TRIGGER {% endcomment %}
                <a class="modal-trigger" href="#modal{{snippet.id}}" style="border: 1px black solid; padding: 2px 15px 2px 15px; border-radius: 2px; background: #eee; position: absolute; bottom: 5px; right: 85px; height: 24px;">EDIT</a>

                <!-- Modal Structure -->
                <div id="modal{{snippet.id}}" class="modal">
                    <div class="modal-content">
                        <form method="POST" action="{% url 'edit_snippet' snippet.id %}">
                            {% csrf_token %}
                            <textarea type="text" class="body" name="body" required>{{snippet.body}}</textarea>
                            <div class="modal-footer">
                                <a href="#!" class="modal-close btn-flat">Cancel</a>
                                <input type="submit" value="SAVE EDITS">
                            </div>                            
                        </form>
                    </div>
                </div>
                {% comment %} DELETE SNIPPET {% endcomment %}
                <form method="POST" action="{% url 'delete_snippet' snippet.id %}" class="inline-flex">
                    {% csrf_token %}
                    <input type="submit" value="DELETE" style="color:salmon; position: absolute; bottom: 5px; right: 5px;">
                </form>

                {% comment %} SCORE (BOTTOM LEFT CORNER) {% endcomment %}
                <div class="score" style="height:14px; width: 10px; background: #fff; border: 1px solid #aaa; position: absolute; bottom: 0; left: 0; font-size: 10px;"></div>
            </div>
        {% empty %}
            <p>You have no snippets. :'(</p>
        {% endfor %}
    </div>
    
    <div class="spacer"></div>




<script>
    const snippets = document.querySelectorAll('.snippet')
    const formSearch = document.querySelector('.form-search')
    const autocomplete = document.querySelector('.autocomplete')
    const searchEl = document.querySelector('.search')
    const btnNewSnippet = document.querySelector('.btn-new-snippet')
    const divNewSnippet = document.querySelector('.div-new-snippet')
    const formNewSnippet = document.querySelector('.form-new-snippet')
    const btnPlusSnippet = document.querySelector('.btn-plus-snippet')
    const wrapper = document.querySelector('.cont-snippets')
    const modalTriggerEls = document.querySelectorAll('.modal-trigger')
    const modals = document.querySelectorAll('.modal');
    //initialize edit modals
    M.Modal.init(modals);

    //keep track of state of 'Control' key
    let controlDown = false;
    document.addEventListener('keydown', (e) => {
        if (e.key === 'Control') controlDown = true
        //control + n will click 'new snippet' button
        if (e.key === 'n' && controlDown) {
            btnNewSnippet.click()
        }
    })
    document.addEventListener('keyup', (e) => {
        if (e.key === 'Control') controlDown = false
    })




    //get an array of arrays, where each child array contains the tags from each group
    const groupEls = document.querySelectorAll('.group')
    const groups = []
    for (let groupEl of groupEls) {
        //console.log('----group name:-------', groupEl.querySelector('.card-title').textContent)
        const tagsForThisGroup = []
        const tagEls = groupEl.querySelectorAll('.group-tag')
        for (let tagEl of tagEls) {
            //console.log(tagEl.textContent);
            tagsForThisGroup.push(tagEl.textContent)
        }
        groups.push(tagsForThisGroup)
    }
    //console.log('groups:', groups);


    const allTagsOnPage = {}
    for (let snippet of snippets) {
        //reduce height of textarea for snippets with minimal text
        const ta = snippet.querySelector('textarea')
        const ta_length = ta.textContent.length
        if (ta_length < 50) {
            ta.style.height = '25px'
        } else if (ta_length >= 200) {
            ta.style.height = '75px'
        }

        //add tag to 'allTagsOnPage' as key.  order snippets based on number of tags
        let score = 0
        const tagsOfSnippet = snippet.querySelectorAll('.tag')
        for (let tag of tagsOfSnippet) {
            score++
            allTagsOnPage[tag.getAttribute('value')] = null
        }
        snippet.style.order = score.toString()
        //'allTagsOnPage' is populated
    }
    
    M.Autocomplete.init(autocomplete, {
        data: allTagsOnPage
    })




    formSearch.addEventListener('submit', (e) => {
        e.preventDefault()

        //make wrapper dissappear for a millisecond 
        wrapper.style.opacity = '0'
        setTimeout(() => {
            wrapper.style.opacity = '1'
        }, 30)

        const searchInputStr = spacify3(searchEl.value).toLowerCase()
        let searchInputStrWithGroups = searchInputStr
        //console.log(`searchInputStr:>${ searchInputStr}<`);

        if (searchInputStr == ' ') {
            console.log('ERROR- nothign entered');
            searchEl.value = ''
        }

        //loop through every search tag - if it belongs to a group, then add the tags from that group to the search string 
        const searchInputArr = spacify1(searchEl.value).toLowerCase().split(' ')
        searchInputArr.forEach(searchTag => {
            groups.forEach(group => {
                if (group.indexOf(searchTag) !== -1) {
                    searchInputStrWithGroups +=  group.join(' ') + ' '
                }
            })
        })

        //calculate score for each snippet
        const orderValues = []
        for (let snippet of snippets) {
            //reset styles
            snippet.style.backgroundColor = 'white'
            snippet.style.opacity = "1"

            const scoreEl = snippet.querySelector('.score')

            let score = 0
            const tags = snippet.querySelectorAll('.tag')
            for (let tag of tags) {
                if (searchInputStrWithGroups.indexOf(` ${tag.getAttribute('value').toLowerCase()} `) !== -1) {
                    //console.log('found this snippet tag in search string: ', tag.getAttribute('value'));
                    score--
                }
            }
            snippet.style.order = score.toString()
            orderValues.push([snippet.getAttribute('value'), snippet.style.order])
            scoreEl.textContent = (score * -1).toString()

            //if snippet has score of 0, make it half transparent
            if (snippet.style.order === "0" && searchEl.value !== "") {
                snippet.style.opacity = "0.5"
            }
        }

        //evaluate 'orderValyues' results, color snippet accordingly (green or yellow)
        orderValues.sort((a,b) => a[1] -  b[1])
        if (orderValues.length >= 2) {
            if (orderValues[0][1] !== orderValues[1][1]) {
                const snippetTop = document.querySelector(`.snippet[value=${orderValues[0][0]}]`)
                snippetTop.style.backgroundColor = '#b8e45d' //greenish
            } else if (orderValues[0][1] !== "0" && orderValues[0][1] === orderValues[1][1]) {
                for (let snippet of snippets) {
                    if (snippet.style.order === orderValues[0][1]) {
                        snippet.style.backgroundColor = "#ffec80" //yellowish
                    }
                }
            }
        }
    })

    //click button to toggle visibility of new snippet form 
    btnNewSnippet.addEventListener('click', () => {
        if (divNewSnippet.style.display === 'none') {
            divNewSnippet.style.display = 'block'
            btnNewSnippet.textContent = '^collapse'
            //focus the textarea
            const bodyEl = divNewSnippet.querySelector('textarea')
            bodyEl.focus()
        } else {
            divNewSnippet.style.display = 'none'
            btnNewSnippet.textContent = 'New Snippet'
            searchEl.focus()
        }
    })

    //Control + Enter will submit a new snippet
    formNewSnippet.addEventListener('keydown', (e) => {
        if (controlDown && e.key === 'Enter') {
            btnPlusSnippet.click()
        }
    })

    //after opening edit modal, select textarea text
    for (let triggerEl of modalTriggerEls) {
        //grab href to see specific modal associaiton
        let modalId = triggerEl.getAttribute('href')
        //remove '#' from modalId
        modalId = modalId.slice(1, modalId.length)
        //get modal that trigger is associated to
        const modalEl = document.querySelector(`div[id=${modalId}]`)
        //get the textarea inside the modal
        const bodyEl = modalEl.querySelector('.body')
        //when trigger is clicked, the bodyEl with be selected
        triggerEl.addEventListener('click', () => {
            setTimeout(() => {
                bodyEl.select()
                console.log('focused');
            }, 50)
        })
    }

function spacify3(string) {
    while (string.indexOf('  ') !== -1) {
        string = string.replace('  ',' ')
    }
    let stringSplit = string.split('')
    if (stringSplit[0] !== ' ') {
        stringSplit.unshift(' ')
        string = stringSplit.join('')
    }
    stringSplit = string.split('')
    if (stringSplit[stringSplit.length - 1] !== ' ') {
        stringSplit.push(' ')
        string = stringSplit.join('')
    }
    return string
}

function spacify1(string) {
    while (string.indexOf('  ') !== -1) {
        string = string.replace('  ',' ')
    }
    let stringSplit = string.split('')
    if (stringSplit[0] === ' ') {
        stringSplit.shift(' ')
        string = stringSplit.join('')
    }
    stringSplit = string.split('')
    if (stringSplit[stringSplit.length - 1] === ' ') {
        stringSplit.pop(' ')
        string = stringSplit.join('')
    }
    return string

}
</script>


{% endblock content %}